version: "3.3"

volumes:
  postgres-data:
    driver: local
  gems:
    driver: local

services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: P4Ssw0rD!

  test:
    image: sismomx/time-bank:development
    command: rspec spec/
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /code
    volumes:
      - .:/code
      - gems:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
      DATABASE_URL: "postgres://postgres:P4Ssw0rD!@db:5432/time-bank_test"
      RACK_ENV: "test"
      RAILS_ENV: "test"
      LC_ALL: C.UTF-8
    links:
      - db

  web: &app
    image: sismomx/time-bank:development
    command: rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /code
    volumes:
      - .:/code
      - gems:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
      DATABASE_URL: "postgres://postgres:P4Ssw0rD!@db:5432/time-bank"
      LC_ALL: C.UTF-8
    links:
      - db

  mailcatcher:
    <<: *app
    command: "mailcatcher --smtp-ip=0.0.0.0 --http-ip=0.0.0.0"
    ports:
      - 1080:1080
      - 1025:1025
