development:
  adapter: postgresql
  encoding: utf8
  database: sismomx-banco-tiempo
  pool: 5
  username: sismomx-banco-tiempo
  password: 123

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sismomx-banco-tiempo_test
  pool: 5
  username: sismomx-banco-tiempo
  password: 123

production:
  adapter: postgresql
  encoding: utf8
  database: sismomx-banco-tiempo_production
  pool: 5
  username: sismomx-banco-tiempo
  password: 123

cucumber:
  <<: *TEST