default: &default
  adapter: postgresql
  encoding: unicode
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sismomx-banco-tiempo
  user: <%= Rails.application.secrets.pg_user %>
  password: <%= Rails.application.secrets.pg_pass %>
  host: localhost

test: &TEST
  <<: *default
  database: sismomx-banco-tiempo_test
  user: postgres
  host: <%= ENV['HOST'] %>

production:
  <<: *default
  database: sismomx-banco-tiempo_production
  username: sismomx-banco-tiempo
  host: postgres
  password: <%= ENV['BITSO_ALERTS_DATABASE_PASSWORD'] %>
